version: '3.7'
# all the containers have to declare inside services
services:
  # App service
  nestchat:
    # application rely on redis running
    depends_on:
      - redis
    # this build context will take the commands from Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    # image name
    image: nest-chat-realtime-docker
    # container name
    container_name: nestchat
    # always restart the container if it stops.
    restart: always
    # docker run -t is allow
    tty: true
    # application port, this is take value from env file
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    # working directory
    working_dir: /var/www/nest-chat-realtime
    # application environment
    environment:
      SERVICE_NAME: nestchat
      SERVICE_TAGS: dev
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
    # save (persist) data and also to share data between containers
    volumes:
      - ./:/var/www/nest-chat-realtime
      - /var/www/nest-chat-realtime/node_modules
      # application network, each container for a service joins this network
    networks:
      - nest-chat-network
  # Redis service
  redis:
    # image name
    image: redis:latest
    # container name
    container_name: redis
    # execute the command once start redis container
    command: [
        "redis-server",
        "--bind",
        "redis",
        "--port",
        "6379"
    ]
    # save (persist) data and also to share data between containers
    volumes:
      - red_data:/var/lib/redis
    # redis port, this is take value from env file
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
      # application network, each container for a service joins this network
    networks:
      - nest-chat-network

  #Docker Networks
networks:
  # All container connect in a network
  nest-chat-network:
    driver: bridge
# save (persist) data
volumes:
  red_data: {}

